/**
 * Standard FictionBook 2.0 genre codes to human-readable names.
 * INPX indexes carry these codes in the `books.genre` column (comma-separated).
 * Unknown codes fall back to a prettified version of the code itself.
 */
export const FB2_GENRE_NAMES: Readonly<Record<string, string>> = {
  sf: 'Science Fiction',
  sf_history: 'Alternate History',
  sf_action: 'Action Science Fiction',
  sf_epic: 'Epic Science Fiction',
  sf_heroic: 'Heroic Science Fiction',
  sf_detective: 'Detective Science Fiction',
  sf_cyberpunk: 'Cyberpunk',
  sf_parapolit: 'Political Science Fiction',
  sf_postapoc: 'Post-apocalyptic',
  sf_teens: 'Teen Science Fiction',
  sf_space: 'Space Opera',
  sf_stimpank: 'Steampunk',
  sf_fantasy: 'Fantasy Science Fiction',
  sf_horror: 'Horror Science Fiction',
  fantasy: 'Fantasy',
  fantasy_epic: 'Epic Fantasy',
  fantasy_action: 'Action Fantasy',
  fantasy_heroic: 'Heroic Fantasy',
  fantasy_sword: 'Sword and Sorcery',
  fantasy_dark: 'Dark Fantasy',
  fantasy_horror: 'Horror Fantasy',
  fantasy_detective: 'Detective Fantasy',
  fantasy_strange: 'Urban Fantasy',
  fantasy_social: 'Social Fantasy',
  fantasy_fable: 'Fable',
  detective: 'Detective',
  det_classic: 'Classic Detective',
  det_police: 'Police Detective',
  det_action: 'Action Detective',
  det_irony: 'Ironic Detective',
  det_history: 'Historical Detective',
  det_espionage: 'Spy Detective',
  det_crime: 'Crime',
  det_political: 'Political Detective',
  det_maniac: 'Thriller',
  det_hard: 'Hard-boiled Detective',
  thriller: 'Thriller',
  thriller_action: 'Action Thriller',
  thriller_espionage: 'Spy Thriller',
  thriller_crime: 'Crime Thriller',
  thriller_maniac: 'Maniac Thriller',
  thriller_police: 'Police Thriller',
  thriller_psychological: 'Psychological Thriller',
  prose: 'Prose',
  prose_classic: 'Classical Prose',
  prose_history: 'Historical Prose',
  prose_contemporary: 'Contemporary Prose',
  prose_counter: 'Counterculture',
  prose_rus_classic: 'Russian Classical Prose',
  prose_su_classics: 'Soviet Classics',
  prose_military: 'Military Prose',
  prose_war: 'War Prose',
  prose_su_contemporary: 'Soviet Contemporary Prose',
  prose_rus_contemporary: 'Russian Contemporary Prose',
  love: 'Romance',
  love_contemporary: 'Contemporary Romance',
  love_history: 'Historical Romance',
  love_detective: 'Detective Romance',
  love_short: 'Short Romance',
  love_erotica: 'Erotica',
  love_sf: 'Science Fiction Romance',
  love_social: 'Social Romance',
  love_fantasy: 'Fantasy Romance',
  adv_western: 'Western',
  adv_history: 'Adventure',
  adv_detective: 'Detective Adventure',
  adv_indian: 'Indian Adventure',
  adv_maritime: 'Maritime Adventure',
  adv_geo: 'Geographic Adventure',
  adv_animal: 'Animal Adventure',
  children: "Children's Literature",
  child_adv: "Children's Adventure",
  child_tale: 'Fairy Tale',
  child_prose: "Children's Prose",
  child_poetry: "Children's Poetry",
  child_art: "Children's Art",
  child_det: "Children's Detective",
  child_education: 'Educational',
  child_sf: "Children's Science Fiction",
  poetry: 'Poetry',
  poetry_classic: 'Classical Poetry',
  poetry_modern: 'Modern Poetry',
  humor: 'Humor',
  humor_anecdote: 'Anecdotes',
  humor_prose: 'Humorous Prose',
  humor_poetry: 'Humorous Poetry',
  humor_satire: 'Satire',
  humor_fantasy: 'Humorous Fantasy',
  dramaturgy: 'Drama',
  dramaturgy_play: 'Plays',
  religion: 'Religion',
  religion_rel: 'Religious Literature',
  religion_esoterics: 'Esoterics',
  religion_self: 'Self-Help',
  religion_philosophy: 'Philosophy',
  science: 'Science',
  science_history: 'History',
  science_psychology: 'Psychology',
  science_culture: 'Cultural Studies',
  science_religion: 'Religious Studies',
  science_philosophy: 'Philosophy',
  science_politics: 'Political Science',
  science_business: 'Business',
  science_juris: 'Law',
  science_world_politics: 'World Politics',
  science_education: 'Education',
  science_medicine: 'Medicine',
  science_geology: 'Geology',
  science_computer: 'Computer Science',
  popular_business: 'Business Literature',
  popular_banking: 'Banking',
  nonf_biography: 'Biography',
  nonf_biography_memoirs: 'Memoirs',
  nonf_biography_military: 'Military Memoirs',
  nonf_publicism: 'Publicism',
  nonf_publicism_essay: 'Essays',
  nonf_publicism_criticism: 'Criticism',
  design: 'Design',
  design_arch: 'Architecture',
  design_art: 'Art',
  design_photo: 'Photography',
  reference: 'Reference',
  reference_encyclopedia: 'Encyclopedia',
  reference_dict: 'Dictionaries',
  reference_guide: 'Guidebooks',
  home_pets: 'Pets',
  home_animal: 'Animals',
  home_cooking: 'Cooking',
  home_craft: 'Crafts',
  home_entertain: 'Entertainment',
  home_garden: 'Gardening',
  home_health: 'Health',
  home_diy: 'DIY',
  home_sex: 'Sexuality',
  computer: 'Computers',
  comp_os: 'Operating Systems',
  comp_prog: 'Programming',
  comp_proglib: 'Programming Libraries',
  comp_prog_lingua: 'Programming Languages',
  comp_hard: 'Hardware',
  comp_db: 'Databases',
  comp_web: 'Web Development',
  comp_soft: 'Software',
  comp_admin: 'Administration',
  comp_security: 'Security',
  comp_dsp: 'Digital Signal Processing',
  comp_math: 'Computational Mathematics',
};

export function resolveFb2GenreName(code: string): string {
  const trimmed = code.trim();
  if (!trimmed) return trimmed;
  return FB2_GENRE_NAMES[trimmed] ?? prettifyGenreCode(trimmed);
}

function prettifyGenreCode(code: string): string {
  return code
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}
